-- 1. Таблица role (справочник ролей)
CREATE TABLE role
(
  role_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  role_name VARCHAR(100) NOT NULL UNIQUE
);

-- 2. Таблица user (пользователи)
CREATE TABLE "user"
(
  user_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_surname VARCHAR(100) NOT NULL,
  user_name VARCHAR(100) NOT NULL,
  user_patronymic VARCHAR(100) NOT NULL,
  user_login TEXT NOT NULL,
  user_password TEXT NOT NULL,
  user_role INT NOT NULL,
  FOREIGN KEY (user_role) REFERENCES role(role_id)
);

-- 3. Таблица manufacturer (производитель)
CREATE TABLE manufacturer
(
  manufacturer_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  manufacturer_name VARCHAR(200) NOT NULL UNIQUE
);

-- 4. Таблица supplier (поставщик)
CREATE TABLE supplier
(
  supplier_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  supplier_name VARCHAR(200) NOT NULL UNIQUE
);

-- 5. Таблица category (категория товара)
CREATE TABLE category
(
  category_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  category_name VARCHAR(200) NOT NULL UNIQUE
);

-- 6. Таблица unit_of_measure (единицы измерения)
CREATE TABLE unit_of_measure
(
  unit_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  unit_name VARCHAR(50) NOT NULL UNIQUE,
  unit_short_name VARCHAR(20) NOT NULL
);

-- 7. Таблица product (товары)
CREATE TABLE product
(
  product_article_number VARCHAR(100) PRIMARY KEY,
  product_type VARCHAR(200) NOT NULL,
  product_model TEXT NOT NULL,
  product_description TEXT NOT NULL,
  product_unit INT NOT NULL,
  product_category INT NOT NULL,
  product_photo VARCHAR(500) NULL,
  product_manufacturer INT NOT NULL,
  product_supplier INT NOT NULL,
  product_cost DECIMAL(19,4) NOT NULL,
  product_max_discount SMALLINT NOT NULL,
  product_current_discount SMALLINT NOT NULL,
  product_quantity_in_stock INT NOT NULL,
  product_status VARCHAR(50) NOT NULL DEFAULT 'В наличии',
  FOREIGN KEY (product_unit) REFERENCES unit_of_measure(unit_id),
  FOREIGN KEY (product_category) REFERENCES category(category_id),
  FOREIGN KEY (product_manufacturer) REFERENCES manufacturer(manufacturer_id),
  FOREIGN KEY (product_supplier) REFERENCES supplier(supplier_id)
);

-- 8. Таблица pickup_point (пункты выдачи)
CREATE TABLE pickup_point
(
  pickup_point_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  pickup_point_address TEXT NOT NULL UNIQUE
);

-- 9. Таблица order_status (статусы заказов)
CREATE TABLE order_status
(
  order_status_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  order_status_name VARCHAR(50) NOT NULL UNIQUE
);

-- 10. Таблица customer (клиенты)
CREATE TABLE customer
(
  customer_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  customer_surname VARCHAR(100) NOT NULL,
  customer_name VARCHAR(100) NOT NULL,
  customer_patronymic VARCHAR(100) NOT NULL,
  customer_code INT NOT NULL UNIQUE
);

-- 11. Таблица order (заказы)
CREATE TABLE "order"
(
  order_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  order_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  order_delivery_date TIMESTAMP NOT NULL,
  order_pickup_point INT NOT NULL,
  order_customer INT NULL,
  order_pickup_code INT NOT NULL,
  order_status INT NOT NULL,
  FOREIGN KEY (order_pickup_point) REFERENCES pickup_point(pickup_point_id),
  FOREIGN KEY (order_customer) REFERENCES customer(customer_id),
  FOREIGN KEY (order_status) REFERENCES order_status(order_status_id)
);

-- 12. Таблица order_product (связь заказов и товаров)
CREATE TABLE order_product
(
  order_id INT NOT NULL,
  product_article_number VARCHAR(100) NOT NULL,
  product_quantity INT NOT NULL,
  PRIMARY KEY (order_id, product_article_number),
  FOREIGN KEY (order_id) REFERENCES "order"(order_id),
  FOREIGN KEY (product_article_number) REFERENCES product(product_article_number)
);

-- ==================== ЗАПОЛНЕНИЕ ДАННЫХ ====================

-- 1. Заполнение role
INSERT INTO role (role_name) VALUES 
('Администратор'),
('Менеджер'),
('Клиент');

-- 2. Заполнение user
INSERT INTO "user" (user_surname, user_name, user_patronymic, user_login, user_password, user_role) VALUES
('Савин', 'Станислав', 'Гордеевич', 'dlh4o1tzrbse@yahoo.com', '2L6KZG', 1),
('Григорьева', 'Есения', 'Александровна', 'rdgm3tpai7ch@outlook.com', 'uzWC67', 1),
('Копылова', 'Алиса', 'Кирилловна', '048anwxsgze1@outlook.com', '8ntwUp', 1),
('Кузнецов', 'Лев', 'Фёдорович', '9zg4lmtik3ja@yahoo.com', 'YOyhfR', 2),
('Иванов', 'Михаил', 'Тимофеевич', '1p4khxif7awq@mail.com', 'RSbvHv', 2),
('Крюков', 'Тимофей', 'Ильич', 'zu56nc4l30xm@outlook.com', 'rwVDh9', 2),
('Игнатов', 'Роман', 'Степанович', 'iuf9onrqs1l4@mail.com', 'LdNyos', 3),
('Анисимова', 'Алисия', 'Сергеевна', 'hkonmlp8tdy2@mail.com', 'gynQMT', 3),
('Лебедева', 'Софья', 'Марковна', '9ovm3eqak0jz@mail.com', 'AtnDjr', 3),
('Волков', 'Богдан', 'Денисович', '5lfozwx7erq2@outlook.com', 'JlFRCZ', 3);

-- 3. Заполнение manufacturer
INSERT INTO manufacturer (manufacturer_name) VALUES 
('ЮвелирКарат'),
('ЮвелирТорг');

-- 4. Заполнение supplier
INSERT INTO supplier (supplier_name) VALUES 
('SunLight'),
('Sokolov');

-- 5. Заполнение category
INSERT INTO category (category_name) VALUES 
('Ювелирные украшения');

-- 6. Заполнение unit_of_measure
INSERT INTO unit_of_measure (unit_name, unit_short_name) VALUES 
('штука', 'шт.');

-- 7. Заполнение product
INSERT INTO product (product_article_number, product_type, product_model, product_description, 
                     product_unit, product_category, product_photo, 
                     product_manufacturer, product_supplier, product_cost, product_max_discount, 
                     product_current_discount, product_quantity_in_stock, product_status) VALUES
('А112Т4', 'Серьги', 'Звезда', 'Серьги серебряные в позолоте продёвки на цепочке "Звезда"', 1, 1, 'А112Т4.png', 1, 1, 590, 30, 3, 6, 'В наличии'),
('G843Y6', 'Подвеска', '2138729/9', 'Подвеска серебряная с фианитами 2138729/9 Ювелир Карат', 1, 1, 'G843Y6.jpg', 1, 2, 240, 25, 3, 6, 'В наличии'),
('G836H6', 'Подвеска', '2139189/9п', 'Подвеска серебряная в позолоте с фианитами 2139189/9п Ювелир Карат', 1, 1, 'G836H6.jpg', 1, 2, 140, 10, 2, 16, 'В наличии'),
('S648N6', 'Серьги', 'Бабочки', 'Серьги "Бабочки" в позолоте', 1, 1, 'S648N6.png', 1, 1, 990, 5, 4, 5, 'В наличии'),
('D493Y7', 'Ожерелье', 'Cordelia', 'Ожерелье Cordelia (муассанит, 11шт, 3,5мм, круг, BS Regular, 40см', 1, 1, 'D493Y7.jpg', 1, 2, 79000, 30, 3, 2, 'В наличии'),
('D936R6', 'Серьги', '2129919/96П', 'Серьги со стразами Swarovski 2129919/96П Ювелир Карат', 1, 1, 'D936R6.jpg', 2, 1, 890, 30, 3, 6, 'В наличии'),
('S395J7', 'Серьги', '029038', 'Серьги из золота 029038', 1, 1, 'S395J7.jpg', 1, 2, 7000, 25, 3, 6, 'В наличии'),
('C635R4', 'Ожерелье', 'Lace', 'Ожерелье Lace (муассанит, круг, BS Regular, 6,5мм, 2 муассанит Кр-57 6мм', 1, 1, 'C635R4.jpg', 2, 1, 590000, 10, 2, 16, 'В наличии'),
('F735H6', 'Серьги', 'С эмалью', 'Серьги из золота с эмалью', 1, 1, 'F735H6.jpg', 2, 2, 12000, 5, 4, 5, 'В наличии'),
('S538J7', 'Серьги', '4 фианита', 'Серьги с 4 фианитами из серебра с позолотой', 1, 1, 'S538J7.jpg', 1, 2, 2300, 30, 3, 2, 'В наличии'),
('V835G5', 'Подвеска', 'Золочёная', 'Подвеска из золочёного серебра с фианитами', 1, 1, NULL, 1, 1, 695, 10, 3, 6, 'В наличии'),
('P846H6', 'Подвеска', 'П142-4547', 'Подвеска из красного золота П142-4547', 1, 1, NULL, 2, 2, 5195, 5, 3, 6, 'В наличии'),
('S530N6', 'Серьги', 'С керамикой', 'Серебряные серьги c ювелирной керамикой', 1, 1, NULL, 1, 1, 2900, 15, 2, 16, 'В наличии'),
('N385N6', 'Серьги', 'Продевки', 'Серьги-продевки из золота с фианитами', 1, 1, NULL, 1, 2, 6200, 20, 4, 5, 'В наличии'),
('K943G6', 'Серьги', 'С эмалью', 'Серьги из золота с эмалью', 1, 1, NULL, 2, 2, 11545, 25, 3, 2, 'В наличии'),
('S844B6', 'Подвеска', 'С позолотой', 'Подвеска из серебра с позолотой', 1, 1, NULL, 2, 1, 2100, 6, 3, 6, 'В наличии'),
('B846B6', 'Браслет', 'Бесконечность', 'Браслет из золота "Бесконечность" яхонт', 1, 1, NULL, 1, 2, 5900, 15, 3, 6, 'В наличии'),
('L486B6', 'Серьги', 'Красное золото', 'Серьги из красного золота', 1, 1, NULL, 1, 2, 7000, 30, 2, 16, 'В наличии'),
('H845N5', 'Серьги', 'С позолотой', 'Серьги из серебра с позолотой', 1, 1, NULL, 2, 1, 2400, 25, 4, 5, 'В наличии'),
('F047G5', 'Брошь', 'PLATINA', 'Брошь PLATINA jewelry из серебра 925 пробы с эмалью', 1, 1, NULL, 1, 2, 7100, 10, 3, 2, 'В наличии'),
('A485H6', 'Кольцо', 'С позолотой', 'Кольцо из серебра с позолотой', 1, 1, NULL, 1, 1, 1110, 5, 4, 11, 'В наличии'),
('B845B6', 'Серьги', 'С фианитами и гематитами', 'Серьги с фианитами и гематитами из серебра с позолотой', 1, 1, NULL, 2, 2, 5200, 30, 3, 6, 'В наличии'),
('L596G5', 'Серьги', 'Красное золото', 'Серьги из красного золота', 1, 1, NULL, 2, 1, 11000, 15, 3, 6, 'В наличии'),
('C453B6', 'Подвеска', 'Красное золото', 'Подвеска из красного золота', 1, 1, NULL, 1, 2, 5300, 25, 2, 16, 'В наличии'),
('B835H6', 'Колье', 'Серебряное', 'Ювелирное колье из серебра 925 пробы с фианитами', 1, 1, NULL, 1, 2, 2600, 20, 4, 5, 'В наличии'),
('P033N7', 'Подвеска', 'Красное золото', 'Подвеска из красного золота', 1, 1, NULL, 1, 1, 4300, 5, 3, 2, 'В наличии'),
('B936H6', 'Колье', 'Эстет', 'Колье Эстет Золотое колье', 1, 1, NULL, 2, 2, 17500, 5, 3, 9, 'В наличии'),
('B964G6', 'Подвеска', 'С бриллиантом', 'Подвеска с 1 бриллиантом из красного золота', 1, 1, NULL, 2, 2, 5350, 5, 2, 6, 'В наличии'),
('N764H5', 'Серьги', 'Без камней', 'Платина Серьги из красного золота без камней', 1, 1, NULL, 1, 1, 10600, 10, 4, 3, 'В наличии'),
('V494H6', 'Подвеска', 'С фианитами', 'Подвеска серебряная с фианитами', 1, 1, NULL, 1, 2, 480, 15, 2, 12, 'В наличии');

-- 8. Заполнение pickup_point
INSERT INTO pickup_point (pickup_point_address) VALUES
('344288, г. Михайловка, ул. Чехова, 1'),
('614164, г. Михайловка, ул. Степная, 30'),
('394242, г. Михайловка, ул. Коммунистическая, 43'),
('660540, г. Михайловка, ул. Солнечная, 25'),
('125837, г. Михайловка, ул. Шоссейная, 40'),
('125703, г. Михайловка, ул. Партизанская, 49'),
('625283, г. Михайловка, ул. Победы, 46'),
('614611, г. Михайловка, ул. Молодежная, 50'),
('454311, г. Михайловка, ул. Новая, 19'),
('660007, г. Михайловка, ул. Октябрьская, 19'),
('603036, г. Михайловка, ул. Садовая, 4'),
('450983, г. Михайловка, ул. Комсомольская, 26'),
('394782, г. Михайловка, ул. Чехова, 3'),
('603002, г. Михайловка, ул. Дзержинского, 28'),
('450558, г. Михайловка, ул. Набережная, 30'),
('394060, г. Михайловка, ул. Фрунзе, 43'),
('410661, г. Михайловка, ул. Школьная, 50'),
('625590, г. Михайловка, ул. Коммунистическая, 20'),
('625683, г. Михайловка, ул. 8 Марта'),
('400562, г. Михайловка, ул. Зеленая, 32'),
('614510, г. Михайловка, ул. Маяковского, 47'),
('410542, г. Михайловка, ул. Светлая, 46'),
('620839, г. Михайловка, ул. Цветочная, 8'),
('443890, г. Михайловка, ул. Коммунистическая, 1'),
('603379, г. Михайловка, ул. Спортивная, 46'),
('603721, г. Михайловка, ул. Гоголя, 41'),
('410172, г. Михайловка, ул. Северная, 13'),
('420151, г. Михайловка, ул. Вишневая, 32'),
('125061, г. Михайловка, ул. Подгорная, 8'),
('630370, г. Михайловка, ул. Шоссейная, 24'),
('614753, г. Михайловка, ул. Полевая, 35'),
('426030, г. Михайловка, ул. Маяковского, 44'),
('450375, г. Михайловка ул. Клубная, 44'),
('625560, г. Михайловка, ул. Некрасова, 12'),
('630201, г. Михайловка, ул. Комсомольская, 17'),
('190949, г. Михайловка, ул. Мичурина, 26');

-- 9. Заполнение order_status
INSERT INTO order_status (order_status_name) VALUES 
('Новый'),
('Завершен'),
('Отменен'),
('В обработке');

-- 10. Заполнение customer
INSERT INTO customer (customer_surname, customer_name, customer_patronymic, customer_code) VALUES
('Игнатов', 'Роман', 'Степанович', 923),
('Лебедева', 'Софья', 'Марковна', 924),
('Анисимова', 'Алисия', 'Сергеевна', 927),
('Волков', 'Богдан', 'Денисович', 929);

-- 11. Заполнение order
INSERT INTO "order" (order_date, order_delivery_date, order_pickup_point, order_customer, order_pickup_code, order_status) VALUES
('2022-05-19 00:00:00', '2022-05-25 00:00:00', 1, NULL, 921, 2),
('2022-05-20 00:00:00', '2022-05-26 00:00:00', 36, NULL, 922, 1),
('2022-05-21 00:00:00', '2022-05-27 00:00:00', 2, 1, 923, 1),
('2022-05-23 00:00:00', '2022-05-29 00:00:00', 11, 2, 924, 1),
('2022-05-23 00:00:00', '2022-05-29 00:00:00', 2, NULL, 925, 2),
('2022-05-24 00:00:00', '2022-05-30 00:00:00', 34, NULL, 926, 2),
('2022-05-25 00:00:00', '2022-05-31 00:00:00', 3, 3, 927, 1),
('2022-05-27 00:00:00', '2022-06-02 00:00:00', 19, NULL, 928, 1),
('2022-05-27 00:00:00', '2022-06-02 00:00:00', 5, 4, 929, 1),
('2022-05-28 00:00:00', '2022-06-03 00:00:00', 25, NULL, 930, 2);

-- 12. Заполнение order_product
INSERT INTO order_product (order_id, product_article_number, product_quantity) VALUES
(1, 'А112Т4', 1),
(1, 'G843Y6', 1),
(2, 'S648N6', 2),
(2, 'D493Y7', 2),
(3, 'C635R4', 1),
(3, 'F735H6', 1),
(4, 'S538J7', 5),
(4, 'V835G5', 5),
(5, 'P846H6', 2),
(5, 'S530N6', 2),
(6, 'S530N6', 1),
(6, 'S844B6', 1),
(7, 'B846B6', 4),
(7, 'L486B6', 2),
(8, 'H845N5', 2),
(8, 'F047G5', 1),
(9, 'C453B6', 1),
(9, 'B835H6', 1),
(10, 'B964G6', 4),
(10, 'N764H5', 5);